services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_python
    environment:
      PYTHONUNBUFFERED: 1
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ecommerce
    working_dir: /app
    volumes:
      - ./data:/app/data # arquivo de entrada
      - ./src:/app/src # Mapeia o código-fonte para dentro do contêiner
      - ./sql:/app/sql # Mapeia os scripts SQL para dentro do contêiner
    depends_on:
      db:
        condition: service_healthy
    command: tail -f /dev/null

volumes:
  db_data:
