services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_python
    working_dir: /app
    volumes:
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
