services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: app_python
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ecommerce
    working_dir: /app
    volumes:
      - ./data:/data # arquivo de entrada
    depends_on:
      db:
        condition: service_healthy
    command: bash -lc "python init_db.py && python load_data.py && python main.py"

volumes:
  db_data:
